{
  "formatVersion": "1.1",
  "component": {
    "url": "../../squircle-shape/5.3.0-js1/squircle-shape-5.3.0-js1.module",
    "group": "com.stoyanvuchev",
    "module": "squircle-shape",
    "version": "5.3.0-js1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "library-js.klib",
          "url": "squircle-shape-js-5.3.0-js1.klib",
          "size": 3492598,
          "sha512": "5de29e59bea95bddc69c296478b3f31f907b36a6d567bdff49904d8ba52a9a8a9df2921bc7b69dd752bb379cc05c02af98490a37fb3dc5abe8e515ca7b258a96",
          "sha256": "c9d23fd86b77cc07444d82257d66101b2d70c3ba05a5cee932a4bc3693218305",
          "sha1": "4e83b014d6d2b3f139903b940e59e26933a1c4c8",
          "md5": "2da17fb88eedd1900a2179ae7c3eb6ad"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "library-js.klib",
          "url": "squircle-shape-js-5.3.0-js1.klib",
          "size": 3492598,
          "sha512": "5de29e59bea95bddc69c296478b3f31f907b36a6d567bdff49904d8ba52a9a8a9df2921bc7b69dd752bb379cc05c02af98490a37fb3dc5abe8e515ca7b258a96",
          "sha256": "c9d23fd86b77cc07444d82257d66101b2d70c3ba05a5cee932a4bc3693218305",
          "sha1": "4e83b014d6d2b3f139903b940e59e26933a1c4c8",
          "md5": "2da17fb88eedd1900a2179ae7c3eb6ad"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "library-js-sources.jar",
          "url": "squircle-shape-js-5.3.0-js1-sources.jar",
          "size": 17284,
          "sha512": "203b5aa17329d125179d2b35d5c67e44aa116dd8b7a72b5c788c6070daaf0225055df935fb284c329af577aca8769e949c311e3ad2268904d39c6c2688d4306d",
          "sha256": "6ce4dc086e4a8793dc0240b84c546eddde11b63d1f6f382a4ef1f30c1136e00a",
          "sha1": "92332182ec768718d7c1fda251ad1570b3989266",
          "md5": "e9af10bf4c4e0bd580fe12302b023447"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "library.kotlin_resources.zip",
          "url": "squircle-shape-js-5.3.0-js1-kotlin_resources.kotlin_resources.zip",
          "size": 330,
          "sha512": "ea920c82741908cc2f5993eff797ab27aa71577254afa171f9732d3a4b83808b2f82617575aa8f65732887356dfd3fb3c56613655e584eff2843911ffd7030b8",
          "sha256": "bade9470f6b33b944ebd242fea05a40cec928044b00f8a09be0bd7cfb4cf0011",
          "sha1": "14245c8a426f84367ddb3cc3e4c2874d00c48141",
          "md5": "3b2995edb4b75ed2be10d2db040d793d"
        }
      ]
    }
  ]
}
