{
  "formatVersion": "1.1",
  "component": {
    "url": "../../squircle-shape/5.3.0-js1/squircle-shape-5.3.0-js1.module",
    "group": "com.stoyanvuchev",
    "module": "squircle-shape",
    "version": "5.3.0-js1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "library.aar",
          "url": "squircle-shape-android-5.3.0-js1.aar",
          "size": 24004,
          "sha512": "948099a11b96b3a4da90afbf15b383bebd1e7cd24f0fcf26aa83ee15a284b487b2297f9fae4c6ceb871b9cfd45f284c9aeaccd39bdadbca22717561854edbc2f",
          "sha256": "e67ab73a43d9df2f81b27806c59317c5aa2662ca1fd0388ef92eea8a934fe27f",
          "sha1": "917527be19365c7c35c0ef29caff6ec39e7edea4",
          "md5": "34b7993c73c04e8f0925c185e8830845"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.11.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "library.aar",
          "url": "squircle-shape-android-5.3.0-js1.aar",
          "size": 24004,
          "sha512": "948099a11b96b3a4da90afbf15b383bebd1e7cd24f0fcf26aa83ee15a284b487b2297f9fae4c6ceb871b9cfd45f284c9aeaccd39bdadbca22717561854edbc2f",
          "sha256": "e67ab73a43d9df2f81b27806c59317c5aa2662ca1fd0388ef92eea8a934fe27f",
          "sha1": "917527be19365c7c35c0ef29caff6ec39e7edea4",
          "md5": "34b7993c73c04e8f0925c185e8830845"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "library-android-sources.jar",
          "url": "squircle-shape-android-5.3.0-js1-sources.jar",
          "size": 17284,
          "sha512": "203b5aa17329d125179d2b35d5c67e44aa116dd8b7a72b5c788c6070daaf0225055df935fb284c329af577aca8769e949c311e3ad2268904d39c6c2688d4306d",
          "sha256": "6ce4dc086e4a8793dc0240b84c546eddde11b63d1f6f382a4ef1f30c1136e00a",
          "sha1": "92332182ec768718d7c1fda251ad1570b3989266",
          "md5": "e9af10bf4c4e0bd580fe12302b023447"
        }
      ]
    }
  ]
}
